<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\desktop_icons.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.7-pre686" />
    <PackageReference Include="Supabase" Version="1.1.1" />
    <PackageReference Include="Supabase.Postgrest" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\desktop_icons.ico" />
  </ItemGroup>

</Project>
